version: 1
policy:
  pullRequests: public
tasks:
  $let:
    proj_name: "docker-exec-websocket-server"
    head_rev:
      $if: tasks_for == "github-pull-request"
      then: ${event.pull_request.head.sha}
      else: ${event.after}
    repository:
      $if: tasks_for == "github-pull-request"
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
    environments:
      - node_image_tag: 16-bullseye
        description: Run tests with node v16
      - node_image_tag: 14-bullseye
        description: Run tests with node v14
      - node_image_tag: 12-bullseye
        description: Run tests with node v12
      - node_image_tag: "10"
        description: Run tests with node v10 (unsupported)
      - node_image_tag: current-bullseye
        description: Run tests with current node version
  in:
    $if: tasks_for == "github-pull-request" && event["action"] in ["opened","reopened","synchronize"]
    then:
      $map: {$eval: environments}
      each(env):
        taskId: {$eval: as_slugid(proj_name + ":node:" + env.node_image_tag + ":tests")}
        deadline:
          $fromNow: 1 day
        taskQueueId: proj-taskcluster/gw-ci-ubuntu-18-04
        metadata:
          name: node:${env.node_image_tag} tests
          description: ${env.description}
          owner: ${event.sender.login}@users.noreply.github.com
          source: ${event.repository.url}
        payload:
          maxRunTime: 3600
          env:
            BUILDKIT_PROGRESS: plain  # auto / tty is over-verbose
            REPO_DIR: {$eval: as_slugid(proj_name + ":node:" + env.node_image_tag + ":tests")}
          mounts:
            - file: bin/docker-compose
              content:
                url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
                sha256: f15a7cd54a85f760a8ece92da63fb85b93036c72ead8056391b8a3fe9dc73134
          command:
            -
              - /bin/bash
              - -vxec
              - |
                docker info
                git --version
                git clone --no-progress "${repository}" "$REPO_DIR"
                chmod a+wrx "$REPO_DIR"
                cd "$REPO_DIR"
                git config advice.detachedHead "false"
                git checkout --no-progress "${head_rev}"
                chmod a+x "/$${USER}/bin/docker-compose"
                "/$${USER}/bin/docker-compose" build --build-arg "NODE_VERSION=${env.node_image_tag}"
                "/$${USER}/bin/docker-compose" run --rm test
